services:
  db:
    image: mysql:8.0
    container_name: comic_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=ComicPlatformDB
    ports:
      - "3307:3306"
    volumes:
      - ./Database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - mysqldata:/var/lib/mysql

  backend:
    build:
      context: ./Backend/ComicPlatform.API
      dockerfile: Dockerfile
    container_name: comic_backend
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=ComicPlatformDB;Uid=root;Pwd=${DB_PASSWORD};
      - ASPNETCORE_ENVIRONMENT=Development
      - AdminSettings__Username=${ADMIN_USERNAME}
      - AdminSettings__Password=${ADMIN_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend/comic-platform-web
      dockerfile: Dockerfile
      args:
        - API_URL=http://backend:8080
    container_name: comic_frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8080
    depends_on:
      - backend

volumes:
  mysqldata:
